CREATE OR REPLACE FUNCION FN_MIGRACION_77()
								RETURNS VARCHAR  AS $$
	DECLARE
		BEGIN
	
		EXCEPTION WHEN OTHERS THEN
			 RETURN 'Error FA_REGISTRA_FACT_COMPRA '|| sqlerrm;
		END;
$$ LANGUAGE 'plpgsql';
	
	
	