
ALTER TABLE fa_tsopd
ADD FOREIGN KEY (SOPD_DSKA)
REFERENCES IN_TDSKA(DSKA_DSKA)
;

ALTER TABLE fa_tsopd
ADD FOREIGN KEY (SOPD_SOLI)
REFERENCES FA_TSOLI(SOLI_SOLI)
;

ALTER TABLE fa_tsopd
ADD FOREIGN KEY (SOPD_KAPR)
REFERENCES in_tkapr(kapr_kapr)
;