INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (1,1,'ANTIOQUIA', 'ANTIOQUIA', 'S','05');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (2,1,'ATLANTICO', 'ATLANTICO', 'S','08');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (3,1,'BOGOTA,D.C.', 'BOGOTA,D.C.', 'S','11');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (4,1,'BOLIVAR', 'BOLIVAR', 'S','13');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (5,1,'BOYACA' , 'BOYACA' , 'S','15');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (6,1,'CALDAS' , 'CALDAS' , 'S','17');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (7,1,'CAQUETA', 'CAQUETA', 'S','18');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (8,1,'CAUCA', 'CAUCA', 'S','19');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (9,1,'CESAR', 'CESAR', 'S','20');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (10 ,1,'CORDOBA', 'CORDOBA', 'S','23');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (11 ,1,'CUNDINAMARCA' , 'CUNDINAMARCA' , 'S','25');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (12 ,1,'CHOCO', 'CHOCO', 'S','27');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (13 ,1,'HUILA', 'HUILA', 'S','41');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (14 ,1,'LAGUAJIRA', 'LAGUAJIRA', 'S','44');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (15 ,1,'MAGDALENA', 'MAGDALENA', 'S','47');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (16 ,1,'META' , 'META' , 'S','50');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (17 ,1,'NARIÑO' , 'NARIÑO' , 'S','52');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (18 ,1,'NORTE DE SANTANDER' , 'NORTE DE SANTANDER' , 'S','54');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (19 ,1,'QUINDIO', 'QUINDIO', 'S','63');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (20 ,1,'RISARALDA', 'RISARALDA', 'S','66');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (21 ,1,'SANTANDER', 'SANTANDER', 'S','68');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (22 ,1,'SUCRE', 'SUCRE', 'S','70');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (23 ,1,'TOLIMA' , 'TOLIMA' , 'S','73');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (24 ,1,'VALLEDELCAUCA', 'VALLEDELCAUCA', 'S','76');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (25 ,1,'ARAUCA' , 'ARAUCA' , 'S','81');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (26 ,1,'CASANARE' , 'CASANARE' , 'S','85');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (27 ,1,'PUTUMAYO' , 'PUTUMAYO' , 'S','86');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (28 ,1,'ARCHIPIELAGO DE SAN ANDRES,PROVIDENCIA Y SANTA CATALINA', 'ARCHIPIELAGO DE SAN ANDRES,PROVIDENCIA Y SANTA CATALINA', 'S','88');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (29 ,1,'AMAZONAS' , 'AMAZONAS' , 'S','91');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (30 ,1,'GUAINIA', 'GUAINIA', 'S','94');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (31 ,1,'GUAVIARE' , 'GUAVIARE' , 'S','95');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (32 ,1,'VAUPES' , 'VAUPES' , 'S','97');
INSERT INTO ub_tdepa(depa_depa ,depa_pais ,depa_nombre ,depa_descripcion ,depa_default,depa_codigo)values (33 ,1,'VICHADA', 'VICHADA', 'S','99');