--
--TABLA EN LA CUAL SE ALMACENARA EL HISTORIAL DE LAS FACTURAS
--
CREATE TABLE FA_THFAC(
HFAC_HFAC				BIGSERIAL			NOT NULL,
HFAC_TIUS				BIGSERIAL     		NOT NULL,
HFAC_FECH				TIMESTAMP DEFAULT NOW()     ,
HFAC_FACT				BIGSERIAL           NOT NULL,
HFAC_COME				VARCHAR(2000)		NOT NULL,
HFAC_CLIE				BIGSERIAL			NOT NULL,
HFAC_ESTA				VARCHAAR(2)			NOT NULL,
PRIMARY KEY(HFAC_HFAC)
);