--
--TABLA DE PRODUCTOS PARAMETRIAZADOS
--
CREATE TABLE IN_TPROPAR(
PROPAR_PROPAR			BIGSERIAL NOT NULL,
PROPAR_DSKA				BIGINT 	  NOT NULL,
PROPAR_TIUS				BIGINT	  NOT NULL,
PROPAR_AUCO				BIGINT	  NOT NULL,
PROPAR_DESC				VARCHAR(2000),
PROPAR_ESTA				VARCHAR(2),
PROPAR_FECH				TIMESTAMP DEFAULT NOW(),
PRIMARY KEY (PROPAR_PROPAR)	
)