

INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (1, 'SISTEMA', 'ADMINISTRADOR', '1234', 'administrdor', '1991-01-14', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (2, 'SERNA HURTADO', 'JUAN CAMILO', '1026272205', 'juan.serna@tornillos7777777.com', '1991-02-09', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (4, 'MUÑOZ SARMIENTO', 'BRYAN DAVID', '987654321', 'info@tornillos7777777.com', '1984-06-20', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (7, 'VALERO BARBOSA', 'LAUREANO', '11210399', 'valero1050@hotmail.com', '1967-04-18', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (8, 'ALDANA', 'JULIETH', '1016062699', 'julieth.juan041013@gmail.com', '1994-01-15', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (9, 'SUAREZ ROBAYO', 'MYRIAM', '39761794', 'myria-32@hotmail.com', '1972-11-12', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (6, 'PACHECO', 'ALEJANDRA', '147852369', 'juancamilo97y@hotmail.com', '1980-04-15', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (3, 'BALLESTEROS MATIZ', 'JORGE CAMILO', '123456789', 'juancamilo97y@gmail.com', '1970-02-25', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (5, 'AGUIRRE', 'FACTURADOR', '852369741', 'luis.serna@tornillos7777777.com', '1980-06-18', NULL, NULL, NULL, NULL, NULL);
INSERT INTO us_tpers (pers_pers, pers_apellido, pers_nombre, pers_cedula, pers_email, pers_fecha_nac, pers_tel, pers_cel, pers_dir, pers_dept_resi, pers_ciudad_resi) VALUES (10, 'PULECIO', 'YOLANDA', '51792811', 'yolanda.pulecio@tornillos7777777.com', '1965-09-23', NULL, NULL, NULL, NULL, NULL);

